### ISSUE TITLE
High Sierra?

### ISSUE THREAD

**Issue by Henrietta1989** [diimdeep/afsctool#3]
Do you know if afsctool works with High Sierra?

**Comment by diimdeep** [comment]
afsctool works only with HFS+, Apple implementing APFS and it probably will be default in High Sierra. APFS don't support compression. I don't know whether you can use HFS+ in High Sierra or will it work at all.

**Comment by gingerbeardman** [comment]
I'm running the High Sierra GM candidate 10.13 Beta (17A362a) on an SSD that has been converted in-place to APFS.

running `afsctool -l ~` shows a bunch of HFS+ compressed files. This makes sense as with in-place conversion you'd expect all features of files present on the drive would persist.

That said, I am not able to compress a file using `afsctool -c filename`.

Still investigating.

Thoughts?

**Comment by gingerbeardman** [comment]
`ditto --hfsCompression` will still HFS+ compress files located on a APFS volume, which is great news!

**Comment by diimdeep** [comment]
you mean it compress files that on APFS?

**Comment by gingerbeardman** [comment]
Yes, ditto compresses files that are on APFS.

**Comment by gingerbeardman** [comment]
In other news...

`afsctool -c filename` fails with:
> Unable to compress file.

`afsctool -l` works OK

`afsctool filename` works OK:
> File is not HFS+ compressed.
and
> File is HFS+ compressed.

`afsctool -v filename` works OK:
(though 4.2MB seems rather high for disk space usage?)
> MacBookPro-Matt:phaser-debug-master matt$ ./afsctool -v dist2/phaser-debug.js 
/Users/matt/Downloads/phaser-debug-master/dist2/phaser-debug.js:
File is HFS+ compressed.
File content type: com.netscape.javascript-source
File size (uncompressed data fork; reported size by Mac OS 10.6+ Finder): 57151 bytes / 57 KB (kilobytes) / 56 KiB (kibibytes)
File size (compressed data fork - decmpfs xattr; reported size by Mac OS 10.0-10.5 Finder): 14507 bytes / 4.2 MB (megabytes) / 4 MiB (mebibytes)
File size (compressed data fork): 14523 bytes / 4.2 MB (megabytes) / 4 MiB (mebibytes)
Compression savings: 74.6%
Number of extended attributes: 0
Total size of extended attribute data: 0 bytes
Approximate overhead of extended attributes: 536 bytes
Approximate total file size (compressed data fork + EA + EA overhead + file overhead): 4195104 bytes / 4.2 MB (megabytes) / 4 MiB (mebibytes)
MacBookPro-Matt:phaser-debug-master matt$

**Comment by gingerbeardman** [comment]
This is interesting. I was looking at a fork of your tool: https://github.com/jrk/afsctool

It seems to have more verbose error logging, and `afsctool -c filename` says:

> Expecting f_type of 17 or 23. f_type is 24.

**Comment by diimdeep** [comment]
BTW here is original author of this tool https://brkirch.wordpress.com/afsctool/

**Comment by gingerbeardman** [comment]
Another fork https://github.com/vfx01j/afsctool says the f_type 24 issue was introduced in Sierra (10.12) though I cannot build that version of the tool so I cannot test that the fix holds on High Sierra.

**Comment by diimdeep** [comment]
Here is more info on how HFS+ implements compression.

http://arstechnica.com/apple/2009/08/mac-os-x-10-6/3/
https://developer.apple.com/legacy/library/technotes/tn/tn1150.html
http://wiki.sleuthkit.org/index.php?title=HFS
https://en.wikipedia.org/wiki/Resource_fork

**Comment by gingerbeardman** [comment]
I think the tool will work once changes to incorporate the new f_type is 24 are made. I'll look into it

**Comment by gingerbeardman** [comment]
OK, fixed version is over here: https://github.com/gingerbeardman/afsctool/releases/tag/10.13

Thanks for hosting this discussion!

**Comment by Henrietta1989** [comment]
So if i understand correctly, it works and if i have old compressed files all is okay?

What if i copy compressed file from APFS to HFS+?

**Comment by gingerbeardman** [comment]
> So if i understand correctly, it works

Yes. Fixed version of afsctool, above, will HFS+ compress new files in High Sierra on HFS+ or APFS filesystems. 

> if i have old compressed files all is okay?

Yes, APFS supports HFS+ compressed files. They don't change during the upgrade or a migration. 

> What if i copy compressed file from APFS to HFS+?

That works OK. Whenever you copy a HFS+ compressed file the copy version will be uncompressed and the original version remains compressed. That's just how macOS deals with HFS+ compressed files. That doesn't change in High Sierra or with APFS.

**Comment by Henrietta1989** [comment]
I dragged afsctool to /usr/local/bin folder in High Sierra. Man Viewer don't show manual even if i refresh it.

This AppleScript works:
`do shell script "sudo /usr/local/bin/afsctool -ckl /some/file/path/here.txt" user name "user" password "pass" with administrator privileges`

Why after compression size is bigger not smaller?

Before compression Finder Get Info:
7 239 744 bytes (7,2 MB on disk)

After compression:
10 717 179 bytes (7 MB on disk, compressed)

If i use -m then i get error "number 22" in Script Editor:
do shell script "sudo /usr/local/bin/afsctool -ckl -m 90971520 /some/file/path/here.txt" user name "user" password "pass" with administrator privileges

When and why to use -f and -i?

"-<level> Compression level to use when compressing (ranging from 1 to 9, with 1 being the fastest and 9 being the best - default is 5)"

Do i use compression level like this: -cki -5

I found afscexpand installed by default in High Sierra.

**Comment by gingerbeardman** [comment]
@Henrietta1989 out of interest: why do you spend so much time compressing files manually with this tool? Are you short on drive space? 

this tool does not have a man page, so it doesn't install one, so you won't be able to find one. 

Run it without any arguments to see what options it has. I use an old version with different options than the most current version. 

Your applescript should quote the file path:
```applescript
do shell script "sudo /usr/local/bin/afsctool -ckl \"/some/file/path/here.txt\"" user name "user" password "pass" with administrator privileges
```

tool keeps file of size in disk is smaller. maybe you're file and already compressed? Can you share it? What sizes do you see when you expand it? 

-m works for me. 22 is not an applescript error, as those are all negative numbers. can you add a screenshot of error on this thread? 

-f compresses original versions of files pointed at by any hard links it comes across in the location you specify. 

-i "inverts" the files processed by the tool. Normally it only compresses files whose content it is sure of. With -i it compresses only those files that it has no idea of their content. not sure why you would ever do this.

finally, yes, compression level is used like that in some versions of the tool. Run it without any arguments to see what options it has.

**Comment by gingerbeardman** [comment]
improved current version is now at https://github.com/RJVB/afsctool

binary of that version: [afsctool.zip](https://github.com/diimdeep/afsctool/files/1504128/afsctool.zip)

@diimdeep feel free to close this thread, I think we're done :)

**Comment by Henrietta1989** [comment]
Does this work with Mojave?

How it handles if i try to compress files in external HFS+ drive in 10.13.5?

**Comment by Henrietta1989** [comment]
Does this work with Mojave?

How it handles if i try to compress files in external HFS+ drive in 10.13.5?

Thanks!
